"""empty message

Revision ID: bbe039cc6480
Revises: eee51bba6020
Create Date: 2020-04-24 07:40:50.762624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe039cc6480'
down_revision = 'eee51bba6020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('nama', table_name='mahasiswa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('nama', 'mahasiswa', ['nama'], unique=True)
    # ### end Alembic commands ###
