"""empty message

Revision ID: eee51bba6020
Revises: 712f8e4b7428
Create Date: 2020-04-24 06:39:22.230743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee51bba6020'
down_revision = '712f8e4b7428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('alamat', table_name='mahasiswa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('alamat', 'mahasiswa', ['alamat'], unique=True)
    # ### end Alembic commands ###
