"""initial migration.

Revision ID: 7447fd27ce43
Revises: 8b527754bf69
Create Date: 2020-04-14 14:25:20.949165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7447fd27ce43'
down_revision = '8b527754bf69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('alamat', sa.String(length=125), nullable=True))
    op.drop_index('no_hp', table_name='user')
    op.create_unique_constraint(None, 'user', ['alamat'])
    op.drop_column('user', 'no_hp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('no_hp', mysql.VARCHAR(length=14), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('no_hp', 'user', ['no_hp'], unique=True)
    op.drop_column('user', 'alamat')
    # ### end Alembic commands ###
