"""initial migration.

Revision ID: 8b527754bf69
Revises: 
Create Date: 2020-04-14 14:20:43.055481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b527754bf69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(length=8), nullable=True),
    sa.Column('nama_mahasiswa', sa.String(length=80), nullable=True),
    sa.Column('no_hp', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_mahasiswa'),
    sa.UniqueConstraint('nim'),
    sa.UniqueConstraint('no_hp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
